on:
  pull_request:
    branches: main
    paths: '**earth*'
  push:
    paths: '**earth*'

name: earth (ubuntu-latest, release)

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: Learner and Parameter Test

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      PKG: earth
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = FALSE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
          key: ${{ matrix.config.os }}-${{ env.PKG }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ env.PKG }}-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install system dependencies
        run: |
          pak::local_system_requirements(execute = TRUE)
          pak::pkg_system_requirements("testthat", execute = TRUE)
        shell: Rscript {0}

      - name: Install package dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE, dependencies = FALSE)
          pak::pkg_install("testthat")
        shell: Rscript {0}

      - name: Session info
        run: |
          sessionInfo()
        shell: Rscript {0}

      - name: Install
        run: |
          pak::local_install()
        shell: Rscript {0}

      - name: Learner test
        run: |
          options(crayon.enabled = TRUE)
          testthat::test_local(filter = sprintf("^%s_", "${{ env.PKG }}"))
        shell: Rscript {0}

      - name: Parameter test
        run: |
          options(crayon.enabled = TRUE)
          testthat::test_local(filter = sprintf("^paramtest_%s_", "${{ env.PKG }}"))
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-${{ env.PKG }}-results
          path: check
